#!/bin/bash

set -e

export VOTING_ID="$(cat .soroban/voting_id)"

export TOKEN_CODE="MYNFT"
export TOKEN_ADMIN="GBHCFFI5ZCRNHW6RZVR5WG7ERSP7NOOVKF36QBB4PVESDCMZQL6OQYEM"
TOKEN_ADMIN_HEX="4e22951dc8a2d3dbd1cd63db1be48c9ff6b9d55177e8043c7d4921899982fce8"
TOKEN_ADMIN_SECRET="SC4OVVO2RKSUXWAPRMOQSHDZL2Q5COBGOFZSF5MWVTYXC2LHVFFSAVEJ"
export SOROBAN_RPC_HOST="http://localhost:8000"
export SOROBAN_RPC_URL="$SOROBAN_RPC_HOST/soroban/rpc"
export SOROBAN_NETWORK_PASSPHRASE="Standalone Network ; February 2017"
export SOROBAN_SECRET_KEY="$TOKEN_ADMIN_SECRET"

cd accounts_setup

python3 ~/Library/Python/3.9/lib/python/site-packages/pipenv/__main__.py run python script.py \
  -l SBGNL7EX2WC4C2Q3ASQBYH7KYY2GV3XNJ4CB5A75WCZFH4ZFOOUFY5QU \
  SBJOK2H4QMH2G6O7V23GBVN4J7RPQQNLF3XBIMRB26QWI6YAHESRTRIJ \
  SDGGKBZURLA6JQIVX27YC2E6QXCIPHGQRYECIJHNZCOQXJFSYBPJBCBQ \
  -c "$TOKEN_CODE" \
  -i "$TOKEN_ADMIN" \
  -s "$TOKEN_ADMIN_SECRET" \
  -u "$SOROBAN_RPC_HOST" \
  -p "$SOROBAN_NETWORK_PASSPHRASE" \
  -f "$SOROBAN_RPC_HOST/friendbot"

echo "Creating 3 demo proposals..."

export SOROBAN_SECRET_KEY="SBGNL7EX2WC4C2Q3ASQBYH7KYY2GV3XNJ4CB5A75WCZFH4ZFOOUFY5QU"
soroban invoke \
  --id "$VOTING_ID" \
  --fn propose \
  --arg "$(cat proposal1.hex)"

export SOROBAN_SECRET_KEY="SBJOK2H4QMH2G6O7V23GBVN4J7RPQQNLF3XBIMRB26QWI6YAHESRTRIJ"
soroban invoke \
  --id "$VOTING_ID" \
  --fn propose \
  --arg "$(cat proposal2.hex)"

export SOROBAN_SECRET_KEY="SDGGKBZURLA6JQIVX27YC2E6QXCIPHGQRYECIJHNZCOQXJFSYBPJBCBQ"
soroban invoke \
  --id "$VOTING_ID" \
  --fn propose \
  --arg "$(cat proposal3.hex)"
